//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackMW2013.Models
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class Chat_Mapping : EntityTypeConfiguration<Chat>
    {
        public Chat_Mapping()
        {                        
              this.HasKey(t => t.Id);        
              this.ToTable("Chats");
              this.Property(t => t.Id).HasColumnName("Id");
              this.Property(t => t.Messege).HasColumnName("Messege").IsRequired();
              this.Property(t => t.TimeStamp).HasColumnName("TimeStamp");
              this.Property(t => t.TreeId).HasColumnName("TreeId");
              this.Property(t => t.MemberId).HasColumnName("MemberId");
              this.HasRequired(t => t.Tree).WithMany(t => t.Chats).HasForeignKey(d => d.TreeId);
              this.HasRequired(t => t.Member).WithMany(t => t.Chats).HasForeignKey(d => d.MemberId);
         }
    }
}
