//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackMW2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int Id { get; set; }
        public int OwnerID { get; set; }
        public int TreeID { get; set; }
        public int TreeMemberID { get; set; }
        public string Messege { get; set; }
        public System.TimeSpan TimeStamp { get; set; }
    }
}
