//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackMW2013.Models
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class Member_Mapping : EntityTypeConfiguration<Member>
    {
        public Member_Mapping()
        {                        
              this.HasKey(t => t.Id);        
              this.ToTable("Members");
              this.Property(t => t.Id).HasColumnName("Id");
              this.Property(t => t.Name).HasColumnName("Name").IsRequired().HasMaxLength(300);
              this.Property(t => t.PhoneNumber).HasColumnName("PhoneNumber").IsRequired().HasMaxLength(16);
              this.Property(t => t.Email).HasColumnName("Email").IsRequired();
              this.Property(t => t.TreeId).HasColumnName("TreeId");
              this.HasRequired(t => t.Tree).WithMany(t => t.Members).HasForeignKey(d => d.TreeId);
         }
    }
}
