//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackMW2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreeOwner
    {
        public TreeOwner()
        {
            this.Chats = new HashSet<Chat>();
            this.TreeMembers = new HashSet<TreeMember>();
        }
    
        public int Id { get; set; }
        public int TreeMemberID { get; set; }
        public string OwnerID { get; set; }
        public int ListID { get; set; }
    
        public virtual ICollection<Chat> Chats { get; set; }
        public virtual ICollection<TreeMember> TreeMembers { get; set; }
    }
}
