//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackMW2013.Models
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class Tree
    {
        public Tree()
        {
            this.Members = new HashSet<TreeMember>();
            this.Chats = new HashSet<Chat>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int OwnerId { get; set; }
    
        public virtual Member Owner { get; set; }
        public virtual ICollection<TreeMember> Members { get; set; }
        public virtual ICollection<Chat> Chats { get; set; }
    }
}
