//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackMW2013.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreeMember
    {
        public TreeMember()
        {
            this.TreeOwners = new HashSet<TreeOwner>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public bool IsOwner { get; set; }
    
        public virtual ICollection<TreeOwner> TreeOwners { get; set; }
    }
}
